;;; Scheme Recursive Art Contest Entry
;;;
;;; Please do not include your name or personal info in this file.
;;;
;;; Title: <Creeper>
;;;
;;; Description:
;;;   <Everytime I finshed building the house
;;;    he shows up behind me
;;;    and I have to start over>

(define (draw)
  ; YOUR CODE HERE
  (pu)
  (setposition -200 -200)
  (color "green")
  (pd)
  (begin_fill)
    (fd 400)
    (rt 90)
    (fd 400)
    (rt 90)
    (fd 400)
    (rt 90)
    (fd 400)
    (rt 90)
  (end_fill)
  (pu)
  (color "black")
  (setposition -80 -160)
  (pd)
  (begin_fill) 
    (fd 130)
    (rt 90)
    (fd 40)
    (lt 90)
    (fd 40)
    (rt 90)
    (fd 80)
    (rt 90)
    (fd 40)
    (lt 90)
    (fd 40)
    (rt 90)
    (fd 130)
    (rt 90)
    (fd 40)
    (rt 90)
    (fd 40)
    (lt 90)
    (fd 80)
    (lt 90)
    (fd 40)
    (rt 90)
    (fd 40)
    (rt 90)
  (end_fill)
  (pu)
  (setposition -120 30)
  (pd)
  (begin_fill)
    (fd 90)
    (rt 90)
    (fd 90)
    (rt 90)
    (fd 90)
    (rt 90)
    (fd 90)
    (rt 90)
  (end_fill)
  (pu)
  (setposition 40 30)
  (pd)
  (begin_fill)
    (fd 90)
    (rt 90)
    (fd 90)
    (rt 90)
    (fd 90)
    (rt 90)
    (fd 90)
    (rt 90)
  (end_fill)
  (ht)
  (exitonclick))

; Please leave this last line alone. You may add additional procedures above
; this line.
(draw)